### PR TITLE
Change README to describe philosophy of a type-safe html-css builder

### PR DESCRIPTION
**Pull request by dillonkearns**
- [ ] TODO Make this your tagline in the URL tag at the top

> Type-safe HTML and CSS builder for elm

### CODE REVIEW

**Comment by tracyloisel** [comment]
That would be pretty useful to merge your README update.

Is it plan to merge this PR ?

**Comment by tibastral** [comment]
I want to do it, but it changes the name of the packet, and I'm not yet ready to change the name. What do you think ?

**Comment by dillonkearns** [comment]
I think you should make an edit to keep the name the same in this pull request and merge it in now!

Best to separate it out into separate smaller steps. You can consider a name change later if you'd like to.

**Comment by tibastral** [comment]
Done, thank you !


On 24 September 2019 at 02:49:29, Dillon Kearns (notifications@github.com)
wrote:

I think you should make an edit to keep the name the same in this pull
request and merge it in now!

Best to separate it out into separate smaller steps. You can consider a
name change later if you'd like to.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/elm-athlete/athlete/pull/25?email_source=notifications&email_token=AAAIDD7QZVKIDSW6FCWANMDQLFPZRA5CNFSM4H4NT5Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7MWHOY#issuecomment-534340539>,
or mute the thread

**Pull request merged**
