### PR TITLE
Add maxHeight minWidth minHeight fullWidth to Block modifiers

### PR DESCRIPTION
**Pull request by CharlonTank**

### CODE REVIEW

**Review by tibastral — COMMENTED** [review]
Seems good,

@ghivert what do you think ?

**Comment by ghivert** [comment]
If it compiles, it works! 😁

**Comment by tibastral** [comment]
I’m not talking about that Guillaume, is it something we want (growing that
file) or not ?

;)


On 26 March 2018 at 16:26:11, Guillaume Hivert (notifications@github.com)
wrote:

If it compiles, it works! 😁

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/elm-bodybuilder/elegant/pull/17#issuecomment-376184548>,
or mute the thread

**Comment by CharlonTank** [comment]
I need those @tibastral :)

**Comment by ghivert** [comment]
Why not? There's only shortcuts. We decided to include shortcuts, so why stop? 😄

**Pull request merged**
